stages:
  - build

image: docker:20.10.15

services:
  - docker:dind

docker_build:
  stage: build
  only:
    refs:
      - main
  script:
    - docker info
    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD https://gaiaxregistry.azurecr.io 
    - docker build -t gaiaxregistry.azurecr.io/frontend:latest .
    - docker push gaiaxregistry.azurecr.io/frontend:latest