stages:
  - build
  - deploy

image: docker:latest

services:
  - docker:dind

docker_build:
  stage: build
  only:
    refs:
      - main
  script:
    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD registry.gitlab.com
    - docker build -t registry.gitlab.com/frontend:latest .
    - docker push registry.gitlab.com/frontend:latest