stages:
  - build

image: docker:latest

services:
  - docker:19-dind

docker_build:
  stage: build
  only:
    refs:
      - main
  script:
    - docker login -u $DREGISTRY_USER -p $DREGISTRY_PASSWORD $CI_REGISTRY
    - export DOCKER_HOST=tcp://localhost:2375 && docker build -t registry.gitlab.com/gaia-x/data-infrastructure-federation-services/por/portal-frontend:latest .
    - docker push registry.gitlab.com/gaia-x/data-infrastructure-federation-services/por/portal-frontend:latest