stages:
  - build
  - deploy

image: docker:latest

services:
  - docker:dind

docker_build:
  stage: build
  only:
    refs:
      - main
  script:
    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD https://gaiaxregistry.azurecr.io 
    - docker build -t gaiaxregistry.azurecr.io/frontend:latest .
    - docker push gaiaxregistry.azurecr.io/frontend:latest

recreate_pods:
  stage: deploy
  only:
    refs:
      - main
  image: mcr.microsoft.com/azure-cli
  script:
    - az login --service-principal --username $AZ_APP_ID --password $AZ_PASSWORD --tenant $AZ_TENANT_ID
    - az account set --subscription $AZ_SUBSCRIPTION_ID
    - az aks install-cli
    - az aks get-credentials --resource-group t-systems-gaia-x-development --name gaiax-k8s-001
    - kubectl rollout restart deployment.apps/frontend -n portal-development
    - kubectl rollout restart deployment.apps/frontend -n portal-test        