stages:
  - build

docker_build:
  stage: build
  image: docker:latest
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  services:
    - name: docker:20-dind
      alias: docker
      command: ["--tls=false"]
  only:
    refs:
      - main
  before_script:
    - docker login -u $DREGISTRY_USER -p $DREGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t registry.gitlab.com/gaia-x/data-infrastructure-federation-services/por/portal-frontend:latest .
    - docker push registry.gitlab.com/gaia-x/data-infrastructure-federation-services/por/portal-frontend:latest