export const SIGN_IN_MENU = 'SIGN_IN_MENU';
export const NOT_SIGN_IN_MENU = 'NOT_SIGN_IN_MENU';
export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const UPDATE_SEARCH_FILTER_CRITERIA = 'UPDATE_SEARCH_FILTER_CRITERIA';
export const UPDATE_PAGE_NUMBER = 'UPDATE_PAGE_NUMBER';
